version: "2"

services:
  orb_ping_demo_clj:
    build: .
    environment:
      - AMQP_PATH=amqp://auriga:auriga@auriga-devbox:5672
      - AMQP_EXCHANGE=topic
      - AMQP_KEY_MESSAGE=message
      - AMQP_KEY_OUTCOMING=outcoming
      - AMQP_QUEUE_INCOMING=orb.ping-demo
    extra_hosts:
      - "auriga-devbox:10.200.5.5"
